### ISSUE TITLE
Unable to view student submissions when visiting Private URL and CodeCheck setup as LTI app

### ISSUE THREAD

**Issue by paulbui** [cayhorstmann/codecheck2#60]
I'm using CodeCheck as an LTI tool with my school district's Canvas instance. I do not see the submission list of students' source code when I visit the Private URL. Grade passback to Canvas is working

**Comment by cayhorstmann** [comment]
You need to view your students's LTI submissions from within Canvas. The private URL only shows submissions that aren't LTI submissions. In Canvas, visit the problem as an instructor, and you should see a button to show the student submissions. If that doesn't work, please email me the URL and a screen shot.

**Comment by paulbui** [comment]
I can view the submissions if I create an "Assignment" with multiple problems; however, if I assign an individual problem through Canvas LTI, I cannot see the submission. There is no button to show student submissions...see attached image.
<img width="1287" alt="Screenshot 2024-10-09 at 10 47 29 AM" src="https://github.com/user-attachments/assets/2349cb00-3056-4e9f-a4bb-aed2f23f3e8a">

**Comment by cayhorstmann** [comment]
What do you see when you click the button "Load 2 CodeCheck: SumOfLengths in a new window"?

**Comment by paulbui** [comment]
It opens a new tab with the codecheck problem in student view / public URL

![image](https://github.com/user-attachments/assets/ce6416a7-798f-4a3b-8644-64174c84e62d)

**Comment by cayhorstmann** [comment]
If you set up an assignment (see https://horstmann.com/codecheck/lti.html#creating-a-codecheck-assignment), then you get the instructor view controls. But if you use a single problem URL for an LTI launch, all you get is the student score in the gradebook. LTI with a single problem is not a commonly used feature in Canvas because few people want a gradebook entry for each problem. I don't even think it is documented. It is intended for Moodle users because Moodle can aggregate LTI problems into a single assignment.

**Comment by jmr-ua-pt** [comment]
@paulbui, I think this means that you can get what you want by creating an assignment with a single problem inside.  This is a small extra step, with some more bookkeeping (the URLs), but will give you access to the full student submissions.

I've done this occasionally (in Moodle), because I want/need more than just the score.

**Comment by paulbui** [comment]
Yep. I'll likely make a feature request in the future
